schema: ../../packages/schema/type-defs.graphqls
documents: "**/*.graphql"
plugins:
    - typescript
    - typescript-operations
    - typescript-react-apollo
respectGitIgnore: true
cacheDir: __generated__
