schema: "**/*.graphqls"
schemaEntrypoint: schema/type-defs.graphqls
documents:
    - "**/*.graphql"
plugins:
    - typescript-operations
    - typescript-react-apollo
config:
    useIndexSignature: true
cacheDir: __generated__
