schema: schema/type-defs.graphqls
documents:
    - "**/*.graphql"
    - "**/*.tsx"
plugins:
    - typescript-operations
    - typescript-react-apollo
schemaPlugins:
    - typescript-urql-graphcache
    - typescript-resolvers
respectGitIgnore: true
cacheDir: .cache
