schema: "schema/type-defs.graphqls"
documents:
    - "**/*.graphql"
    - "**/*.tsx"
    - "!shouldBeIgnored1"
plugins:
    - typescript
    - typescript-operations
    - typescript-react-apollo
respectGitIgnore: true
config:
    useIndexSignature: true
cacheDir: __generated__
