schema: "schema/type-defs.graphqls"
schemaEntrypoint: "schema/type-defs.graphqls"
documents: "**/*.graphql"
plugins:
    - typescript-operations
    - typescript-react-apollo
respectGitIgnore: true
config:
    useIndexSignature: true
